name: Run QEMU Example

on: [push, pull_request]

jobs:
  run-qemu:
    runs-on: ubuntu-latest
    steps:
    - name: Dependencies
      run: |
        sudo apt-get update
        sudo apt-get upgrade


    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install -y qemu-system-avr

    - name: Install QEMU static binaries
      run: |
        docker run --rm --privileged docker.io/tonistiigi/binfmt:latest --install arm64,riscv64,arm

    - name: Run QEMU
      run: |
        echo "Running QEMU..."
        qemu-system-avr --version

    - name: Test QEMU
      run: |
        git clone https://github.com/RahulRNandan/LED_Blink_AVR.git
        cd LED_Blink_AVR

        qemu-system-avr -M arduino-uno -kernel build/main.elf -d in_asm,cpu -nographic


        
      
